<script type="text/javascript" src="<?= base_url() ?>assets/js/jquery-3.7.1.min.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/jquery-ui.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/select2.min.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/bootstrap.bundle.min.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/moment.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/bootstrap-datetimepicker.min.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/toastr.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/bootbox.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/message.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/url.js?"></script>
<script type="text/javascript" src="<?= base_url() ?>assets/js/sidebar.js?"></script>